#define COMMAND_POWER_OFF 0
#define COMMAND_POWER_ON 1
#define COMMAND_SET_BRIGHTNESS 2
#define COMMAND_SET_COLOR 3
#define COMMAND_START_AMBILIGHT 4
#define COMMAND_SET_AMBILIGHT_COLOR 5
#define COMMAND_STOP_ANIMATION 6
